Mobile first
Balikuddembe/capstone-project-1 pull request #1
Opened 2022-09-16 16:23 UTC by Balikuddembe

## In this capstone project-1,I have implemented the following features using HTML/CSS and JavaScript.
-Responsive website:
- Adaptive to both mobile and desktop devices
- Part of the contents is displayed dynamically from JavaScript file.
- When you click on a navigation link it will take you to the necessary page.
- The mobile Hamburger will open and close menu on small screen devices
- The hamburger menu is hidden on larger screens.
- And this is a loom link of a recorded demo:

https://www.loom.com/share/fafce362984d4d01ad7fae4d208451ba

2022-09-16 18:26 UTC, Qoosim requested changes
# *Status: Required Changes* :recycle:

Hi @Balikuddembe, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Top Highlights

-   No linter errors. :heavy_check_mark:
-   Good README file. :heavy_check_mark:
-   Correct GitHub Flow. :heavy_check_mark:
-   Good Presentation Video. :heavy_check_mark:
-   Good Project UI. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/94551484/190492897-0ac7634e-6ab4-4ef2-bd1e-d82c813fedc7.gif)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

- [ ] Kindly look into the live version link to your project. It's currently broken. I get 404 error when trying to open it.

- [ ] It is required to follow the guiding template as close as possible. Kindly look into the left position of the hamburger icon on the given template and move yours too from the right to the left. Look at the both designs

### Your Design

![your-hamburger](https://user-images.githubusercontent.com/26597432/190692978-11ac0810-2e7b-4cd0-baa5-7bec6a06a43d.png)

### Provided Design

![given-hamburger](https://user-images.githubusercontent.com/26597432/190693016-92e35341-8a25-49e4-94ff-b385e1a713ba.png)

- [ ] Kindly check the logout link on the black part of the given design and change yours from login to logout. You are only allowed to change the content of the body, not the layout of the page. Please take a look at the both designs

### Your Design

![your-logout](https://user-images.githubusercontent.com/26597432/190693467-3aa5a852-6552-4a75-b034-6f0c3ef9dcd7.png)

### Given Design

![given-logout](https://user-images.githubusercontent.com/26597432/190693505-11299c00-0d14-4d31-853e-b0d094c8ca09.png)

- [ ] On the mobile version, both parts of the navbar get disappears, and the hamburger replaces them. Kindly take a look at both designs.

### Your Design

![your-hamburger](https://user-images.githubusercontent.com/26597432/190694426-93bed2ff-1996-4c95-894b-415daad74eff.png)

### Given hamburger

![given-hamburger](https://user-images.githubusercontent.com/26597432/190694523-c5940592-4093-406c-9eaf-a91b1e7f54ad.png)

- [ ] It is required to produce a close replica of the guiding template. This involves, font-size, font-weight, color - for both the text and background, margin and padding, among others. Kindly look into your footer margin and padding and work that section in line with the given template. Please, take a look at both designs

### Your Design for Home Page

![your-footer](https://user-images.githubusercontent.com/26597432/190697076-b344d718-5554-4752-8bd9-c44dad20543f.png)


### Guiding Template for Home page

![given-footer](https://user-images.githubusercontent.com/26597432/190696175-238bfca5-c628-49a6-8fee-407acc06825c.png)


### Your Design for About page

![your-about-footer](https://user-images.githubusercontent.com/26597432/190696355-1111f882-a761-46f2-96ce-1335ef35d1eb.png)


### Guiding Template for About page

![given-about-footer](https://user-images.githubusercontent.com/26597432/190696555-883e8833-f581-4771-85df-33069ea9a1aa.png)

- [ ] On the main-program section of your project for mobile, each of the article is supposed to be organized in a vertical column. Take a look at both designs.

### Your design

![main-program-mobile](https://user-images.githubusercontent.com/26597432/190700260-d0e30569-1db3-4c51-9b15-0159dbaa2a9d.png)

### Guiding Template

![given-main-program-mobile](https://user-images.githubusercontent.com/26597432/190700324-034c3338-0734-4e41-8181-28af41e81874.png)

- [ ] The same is true for your feature section for the mobile. Kindly take a look and fix them together.

### Your Design

![your-feature-mobile](https://user-images.githubusercontent.com/26597432/190700706-11beb0cd-9b34-48ec-a61c-12c3f9f323d6.png)


### Guiding Template

![given-featured-mobile](https://user-images.githubusercontent.com/26597432/190700772-931ea21a-de85-4ad7-930d-7da522ba836c.png)

- [ ] For your mobile about page, partner section is missing on your design. Kindly look at them and work your design in line with the provided template. Also, increase the width of your two image to match what we have on the guiding template.

### Your Design

![your-about-mobile](https://user-images.githubusercontent.com/26597432/190701241-14351681-f630-4a36-bd57-e1ac9abebb7b.png)

### Guiding Template

![given-about-mobile](https://user-images.githubusercontent.com/26597432/190701305-b71a3645-ea55-4011-8ce5-51910a95c835.png)

2022-09-16 18:26 UTC, Qoosim commented on README.md
> +## Live Demo
- [ ] This link is broken, Kindly look into it and make it work.

2022-09-16 18:26 UTC, Qoosim commented on index.html
> +                            </div>
- [ ] Kindly use the semantic tag `<article>`, instead of ordinary <div> tag, this is great for repetitive content like this.

2022-09-16 18:26 UTC, Qoosim commented on index.js
> +            <img src="${featureD.image}" alt="">
- [ ] Let us always remember to make use of the `alt` attribute for the screen readers benefits. Quick reminder can be find [here](https://www.w3.org/WAI/test-evaluate/preliminary/#images)

2022-09-16 22:53 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Balikuddembe 👋 
Great job on implementing some of the changes requested by the first reviewer 👍 Don't give up there are a few changes that still need to be implemented in order to proceed to the next project 💯 Please make sure to implement all the changes to get approved on your next submission⭐    

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
_Please check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 22:53 UTC, ha-manel commented on index.html
> +                </div>
- [ ] Kindly move the hamburger button to the left side like the previous reviewer asked 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/190826849-131e9d8d-c699-4553-9d84-aa3030d53fb1.png)

## Guidelines:
![image](https://user-images.githubusercontent.com/50721479/190826887-6534128a-e728-4622-92d2-d0d90080cc30.png)

2022-09-16 22:53 UTC, ha-manel commented on index.html
> +        </div>
- [ ] Kindly hide this navbar in the mobile view like the previous reviewer asked and as provided in the guidelines.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/190826980-a4b167ea-d5ad-4acc-8ce5-1314f87be5a2.png)

## Guidelines:
![image](https://user-images.githubusercontent.com/50721479/190826995-29dce62d-7369-4259-a969-8cec4f39ff6f.png)

2022-09-16 22:53 UTC, ha-manel commented on index.html
> +    </footer>
- [ ] Kindly update the footer with the right background-color and the positioning of the text as the previous reviewer asked 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/190827067-c6c48599-c917-4024-8e4d-4a00b3bcf24a.png)

## Guidelines:
![image](https://user-images.githubusercontent.com/50721479/190827075-de42e926-fb45-40bb-8117-57122f0afade.png)

2022-09-16 22:53 UTC, ha-manel commented on about.html
> +    </footer>
- [ ] Kindly update the footer with the right background-color and the positioning of the text as the previous reviewer asked 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/190827172-1f4a1aa6-ccab-48f0-88b4-dd212be57f39.png)

## Guidelines:
![image](https://user-images.githubusercontent.com/50721479/190827184-944eebe9-e502-4147-bf9f-300c30d0bf2d.png)

2022-09-16 22:53 UTC, ha-manel commented on about.html
> +        <section class="history">
- [ ] Kindly add the partners sections after the past events section as provided in the design guidelines and as requested by the previous reviewer 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/190827346-060129ba-0b58-42fe-8d69-8fce4431467c.png)

## Guidelines:
![image](https://user-images.githubusercontent.com/50721479/190827370-5f05a820-df15-4407-98e5-5615823d766a.png)

2022-09-16 22:53 UTC, ha-manel commented on index.html
> +                            <div class="program-item">
- [ ] Kindly change the `div` tags with the class of `program-item` to `article` tags as requested by the previous reviewer.

2022-09-17 10:35 UTC, emmiiorji approved these changes
Hi @Balikuddembe, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![congrats](https://user-images.githubusercontent.com/20554583/190852230-5f3817ec-f592-405d-b627-261e19dd2b16.gif)

## Good Highlights✔

- Requested changes have been implemented
- Live link is now active
- GitHub flow is adhered to
- Good commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 10:35 UTC, emmiiorji commented on style.css
> +    display: none;
[Optional] I recommend that you avoid leaving out commented pieces of code in order to have a neater code base. The commit history can be useful to go back in time.

2022-09-17 14:20 UTC, merged